name: 'Upgrade integration test'
description: 'Runs upgrade suite of integration tests'
inputs:
  upgrade-image-name:
    description: 'Image that will api-gateway be upgraded to'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "test-cluster-1"
        args: >-          
          --agents 2
          --servers-memory=16g
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --k3s-arg "--disable=traefik@server:0"
    - name: Add local.kyma.dev to /etc/hosts
      shell: bash
      run: |
        sudo echo "127.0.0.1 local.kyma.dev" | sudo tee -a /etc/hosts
    - name: Run upgrade integration test
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        OIDC_ISSUER_URL: ${{ secrets.OIDC_ISSUER_URL }}
        KYMA_DOMAIN: "local.kyma.dev"
      run: |
        kubectl config use-context k3d-test-cluster-1
        EXPORT_RESULT=true TEST_UPGRADE_IMG=${{ inputs.operator-image-name }} make install-kyma test-upgrade
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: html-reports
        path: tests/integration/reports/
