apiVersion: batch/v1
kind: CronJob
metadata:
  name: oathkeeper-jwks-rotator
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          initContainers:
            - name: keys-generator
              image: "europe-docker.pkg.dev/kyma-project/prod/tpi/k8s-tools:v20230911-40bb7860"
              command:
                - /bin/sh
                - -c
                - |
                  oathkeeper credentials generate --alg RS256 > /etc/secrets/jwks.json
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                runAsGroup: 10001
                runAsNonRoot: true
                runAsUser: 10000
              volumeMounts:
                - name: {{ .OathkeeperName }}-keys-volume
                  mountPath: /etc/secrets
          containers:
          - name: keys-supplier
            image: europe-docker.pkg.dev/kyma-project/prod/external/oryd/oathkeeper:v0.38.25-beta.1
            command:
            - /bin/bash
            - -c
            - |
              set -e
              kubectl create secret generic {{ .OathkeeperName }}-jwks-secret \
                --from-file=/etc/secrets/jwks.json \
                -n kyma-system -o yaml --dry-run | kubectl apply -f -
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              runAsGroup: 65534
              runAsNonRoot: true
              runAsUser: 65534
            volumeMounts:
            - name: {{ .OathkeeperName }}-keys-volume
              mountPath: /etc/secrets
              readOnly: true
          volumes:
          - name: {{ .OathkeeperName }}-keys-volume
            emptyDir: {}
          restartPolicy: OnFailure
          serviceAccountName: ory-oathkeeper-keys-service-account