kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .ServiceAccountName }}
    namespace: {{ .Namespace }}
roleRef:
  kind: Role
  name: ory-oathkeeper-keys-job-role
  apiGroup: rbac.authorization.k8s.io